grid_map_topic: /dist_transform/grid_map
grid_map_visualizations:
  - name: elevation_points
    type: point_cloud
    params:
     layer: elevation
  - name: dist_elevation_points
    type: point_cloud
    params:
     layer: dist_elevation
  - name: original
    type: occupancy_grid
    params:
     layer: original
     data_min: 0
     data_max: 100
  - name: distance_transform
    type: occupancy_grid
    params:
     layer: distance_transform
     data_min: 0
     data_max: 100
  - name: elevation_cells
    type: grid_cells
    params:
      layer: distance_transform
      lower_threshold: 0.0
      upper_threshold: 0.5
